name: Playwright API Tests
on:
  push:
    paths:
      - "src/**" # Covers api, factories, fixtures, tests, types, etc.
      - "playwright.config.ts" # Catch global config changes
      - "package.json" # Catch new dependency installs
      - "package-lock.json"
  workflow_dispatch: # This allows the manual "Run Workflow" button to appear

jobs:
  test:
    runs-on: ubuntu-latest # Uses a standard Linux machine
    steps:
      - uses: actions/checkout@v4 # 1. Copies your code to the machine

      - name: Setup Node.js
        uses: actions/setup-node@v4 # 2. Installs Node.js
        with:
          node-version: "20"
          cache: "npm" # Speeds up future runs by caching packages

      - name: Install dependencies
        run: npm ci # 3. Installs your project's libraries

      - name: Run Playwright tests
        env:
          # This maps your GitHub Secret to the variable Playwright uses
          RENDER_STAGING_URL: ${{ secrets.RENDER_STAGING_URL }}
        run: npx playwright test # 4. Executes the tests

      - name: Get Allure History
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: gh-pages/allure-history
          keep_histories: 20

      - name: Deploy Allure Report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: allure-report

      - name: Upload Test Report
        if: always() # Always runs even if tests fail
        uses: actions/upload-artifact@v4 # 5. Saves your test results
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
